<!--menu system -->

  <div class="tab-container">
    <div class="container">
      <ul class="tabs cf">
        <li class="tab__list">
          <a class="tab__link" href="../home/">Home</a>
        </li>
        <li class="tab__list">
          <a class="tab__link" href="../classes/">Classes</a>
        </li>
        <li class="tab__list">
          <a class="tab__link tab__link--active" href="../projects/">Projects</a>
        </li>
        <li class="tab__list">
          <a class="tab__link" href="../publications/">Publications</a>
        </li>
      </ul>
    </div>
  </div>
<!--end menu system -->
