<!-- body -->
<!-- div -->
</div>

<!--
<div class="container type--center">
          <p class="type--red milli"><strong>This page is a mock-up of an experimental version of the 
            <a href="http://www.csun.edu/faculty">Faculty App</a>.  Hence, not all the intended functionality 
            of this page has been implemented. </strong>
          </p>
</div>
-->

<!--
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-sm-5">
          <div class="row">
            <div class="col-sm-3 footer-seal">
              <img src="../includes/footer-seal.png" alt="Seal for California State University, Northridge">
            </div>
            <div class="col-sm-9">
              <ul class="list--unstyled">
                <li><strong>META+LAB</strong> <br>© California State University, Northridge</li>
                <li>18111 Nordhoff Street, Northridge, CA 91330</li>
                <li>Phone: (818) 677-1200 / <a href="https://www.csun.edu/contact/" target="_blank">Contact Us</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-sm-7">
          <div class="row">
            <div class="col-sm-4">
              <ul class="list--unstyled">
                <li><a href="https://www.csun.edu/emergency/" target="_blank">Emergency Information</a></li>
                <li><a href="https://www.csun.edu/afvp/university-policies-procedures/" target="_blank">University Policies &amp; Procedures</a></li>
              </ul>
            </div>
            <div class="col-sm-4">
              <ul class="list--unstyled">
                <li><a href="https://www.csun.edu/sites/default/files/900-12.pdf" target="_blank">Terms and Conditions for Use</a></li>
                <li><a href="https://www.csun.edu/sites/default/files/500-8025.pdf" target="_blank">Privacy Policy</a></li>
                <li><a href="https://www.csun.edu/it/document-viewers" target="_blank">Document Reader</a></li>
              </ul>
            </div>
            <div class="col-sm-4">
              <ul class="list--unstyled">
                <li><a href="https://www.calstate.edu/" target="_blank">California State University</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
-->

  <script src="../includes/metaphor.js"></script>

</body></html>
